networks:
  dns_net:
    driver: bridge

services:
  unbound:
    image: alpinelinux/unbound:latest-aarch64
    container_name: unbound
    networks:
      - dns_net
    volumes:
      - './unbound.conf:/etc/unbound/unbound.conf'
      - './root.hints:/etc/unbound/root.hints'
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - dns_net
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: "Africa/Cairo"                             # set your time zone
      FTLCONF_webserver_api_password: 'change me'    # set your pihole web password

      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_dns_upstreams: "unbound#53"

    volumes:
      - './etc-pihole:/etc/pihole'
    restart: unless-stopped
    depends_on:
      - unbound
